import {
  Angular,
  Docker,
  Express,
  Git,
  GitHub,
  JavaScript,
  Jest,
  MobX,
  MongoDB,
  NestJS,
  NextJS,
  NodeJS,
  PostgreSQL,
  React,
  Redux,
  RxJS,
  Sass,
  Tailwind,
  TypeScript,
  Vite,
  Vitest,
  Zustand,
} from '@/shared/ui/icons';

export const technologies = [
  {
    title: 'Frontend',
    stack: [
      { icon: Sass, name: 'SASS/SCSS' },
      { icon: Tailwind, name: 'Tailwind CSS' },
      { icon: JavaScript, name: 'JavaScript' },
      { icon: TypeScript, name: 'TypeScript' },
      { icon: React, name: 'React' },
      { icon: NextJS, name: 'Next' },
      { icon: Angular, name: 'Angular' },
      { icon: Redux, name: 'Redux/Redux Toolkit' },
      { icon: Zustand, name: 'Zustand' },
      { icon: MobX, name: 'MobX' },
      { icon: RxJS, name: 'RxJS' },
      { icon: Jest, name: 'Jest' },
      { icon: Vitest, name: 'Vitest' },
    ],
  },
  {
    title: 'Backend',
    stack: [
      { icon: NodeJS, name: 'Node.js' },
      { icon: Express, name: 'Express' },
      { icon: NestJS, name: 'Nest' },
      { icon: MongoDB, name: 'MongoDB' },
      { icon: PostgreSQL, name: 'PostgreSQL' },
    ],
  },
  {
    title: 'Other',
    stack: [
      { icon: Vite, name: 'Vite' },
      { icon: Docker, name: 'Docker' },
      { icon: Git, name: 'Git' },
      { icon: GitHub, name: 'Github Actions' },
    ],
  },
];
